# Generated by Django 2.0.7 on 2018-07-08 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='login',
            table='user_login',
        ),
    ]
