# Generated by Django 2.0.7 on 2018-07-09 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('attribute_name', models.CharField(max_length=255)),
                ('attribute_type', models.CharField(max_length=255)),
                ('attribute_value', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'config',
            },
        ),
    ]
