# Generated by Django 2.0.7 on 2019-06-05 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0002_auto_20190605_0445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycinfo',
            name='uuid',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
