# Generated by Django 2.0.7 on 2019-06-05 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0003_auto_20190605_0708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kycinfo',
            name='constituency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voters', to='constituency.Constituency'),
        ),
        migrations.AlterField(
            model_name='kycinfo',
            name='polling_booth',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booth_voters', to='polling_booth.PollingBooth'),
        ),
    ]
