# Generated by Django 2.0.7 on 2019-06-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0005_kycinfo_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycinfo',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
