# Generated by Django 2.0.7 on 2019-06-09 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0006_kycinfo_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycinfo',
            name='name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
