# Generated by Django 2.0.7 on 2019-08-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0007_kycinfo_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycinfo',
            name='age',
        ),
        migrations.AddField(
            model_name='kycinfo',
            name='dob',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kycinfo',
            name='voterId',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
