# Generated by Django 2.0.7 on 2019-08-17 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0008_auto_20190817_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycinfo',
            name='kyc_done',
        ),
        migrations.AddField(
            model_name='kycinfo',
            name='verification_status',
            field=models.BooleanField(default=False),
        ),
    ]
