# Generated by Django 2.0.7 on 2019-08-17 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0009_auto_20190817_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='kycinfo',
            name='dob_string',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
