# Generated by Django 2.0.7 on 2019-08-17 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyc', '0010_kycinfo_dob_string'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kycinfo',
            name='voterId',
        ),
        migrations.AddField(
            model_name='kycinfo',
            name='voter_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
